# Prometheus Configuration
global:
  scrape_interval: 15s

scrape_configs:
  # Scrape metrics from the OpenTelemetry Collector itself
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics from Service A
  - job_name: 'service-a'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-a:8080']
  
  # Scrape metrics from Service B
  - job_name: 'service-b'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-b:8081']