# Configuration for Service A

# Spring Application Name - Used for metrics and logging
spring:
    application:
        name: service-a

# Server settings
server:
    port: 8080

# OpenTelemetry Configuration
management:
    # Enable all web endpoints for management (health, info, prometheus, etc.)
    endpoints:
        web:
            exposure:
                include: "*"

    # Configure tracing behavior
    tracing:
        sampling:
            probability: 1.0

    # Configure Opentelemetry Protocol (OTLP)
    otlp:
        tracing:
            # Endpoint for sending traces
            endpoint: http://otel-collector:4318/v1/traces
        metrics:
            # Endpoint for sending metrics
            endpoint: http://otel-collector:4318/v1/metrics
    prometheus:
        metrics:
            export:
                enabled: true
        
        
        # Resilience4j Circuit Breaker Configuration
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 5s
                permittedNumberOfCallsInHalfOpenState: 3
        instances:
            serviceB:
                baseConfig: default
                ignoreExceptions:
                    - org.springframework.web.reactive.function.client.WebClientRequestException
                    - java.util.concurrent.TimeoutException

    # Resilience4j Retry Configuration
    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 1s
                retryExceptions:
                    - org.springframework.web.reactive.function.client.WebClientRequestException
                    - java.util.concurrent.TimeoutException
        instances:
            serviceBRetry:
                baseConfig: default

    # Resilience4j Time Limiter Configuration
    timelimiter:
        configs:
            default:
                timeoutDuration: 2s
                cancelRunningFuture: true
        instances:
            serviceBTimeLimiter:
                baseConfig: default

# Logging Configuration
# logging:
#     level:
#         io.github.resilience4j: DEBUG
#         org.springframework.aop: TRACE