# Configuration for Service A

# Spring Application Name - Used for metrics and logging
spring:
    application:
        name: service-a

# Server settings
server:
    port: 8080

# OpenTelemetry Configuration
management:
    # Enable all web endpoints for management (health, info, prometheus, etc.)
    endpoints:
        web:
            exposure:
                include: "*"

    # Configure tracing behavior
    tracing:
        sampling:
            probability: 1.0

    # Configure Opentelemetry Protocol (OTLP)
    otlp:
        tracing:
            # Endpoint for sending traces
            endpoint: http://otel-collector:4318/v1/traces
        metrics:
            # Endpoint for sending metrics
            endpoint: http://otel-collector:4318/v1/metrics
    prometheus:
        metrics:
            export:
                enabled: true
        
        #TODO: Resilience4j